### ISSUE TITLE
Images in the upper level folder overrides those in the lower level folder

### ISSUE THREAD

**Issue by Baytars** [chrobaktruhlik/spfx-lightbox-image-gallery#7]
Yet another bug found ... Structure of my picture library looks like below:
```
A.jpg
B.jpg
subfolder/
    C.jpg
    D.jpg
    E.jpg
```
When I navigate to `subfolder/` and click `C.jpg` in this webpart, the image shown is `A.jpg` and the carousel below contains these images: `A.jpg`, `B.jpg`, `E.jpg`. Neither `C.jpg` nor `D.jpg` is found. They are overridden by `A.jpg` and `B.jpg`.

**Comment by chrobaktruhlik** [comment]
Yes, you're right. It's a bug in the original version I started from. Wait for the new version. This is already resolved.

**Comment by chrobaktruhlik** [comment]
Fixed in 2.0.0
